### PR TITLE
Ruby 3.1 support

### LINKED ISSUE #121: Support Ruby 3.1
microformats-ruby doesn't support Ruby v3.1.x.

```
Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    Ruby (~> 3.1.2.0)

    microformats (~> 4.3, >= 4.3.1) was resolved to 4.3.1, which depends on
      Ruby (< 3.1, >= 2.4)
```

### PR DESCRIPTION
**Pull request by Terreii**
Fixes #121.

### CODE REVIEW

**Comment by dissolve** [comment]
not sure why travis-ci failed or still things its waiting for response

**Review by dissolve — APPROVED** [review]
All looks good to me

**Comment by Terreii** [comment]
Thanks.

**Comment by dissolve** [comment]
its pending next release.  I want to get travis working again first

**Pull request merged**
